Added version 5.1.2567

diff --git a/update_notifier/thirdparty/wxWidgets/build/update-setup-h b/update_notifier/thirdparty/wxWidgets/build/update-setup-h
--- a/update_notifier/thirdparty/wxWidgets/build/update-setup-h
+++ b/update_notifier/thirdparty/wxWidgets/build/update-setup-h
@@ -5,7 +5,7 @@
 #             having special comment markers in them will be update using
 #             include/wx/setup_inc.h contents
 # Created:    2005-01-15
-# Copyright:  (c) 2005 Vadim Zeitlin <vadim@wxwindows.org>
+# Copyright:  (c) 2005 Vadim Zeitlin <vadim@wxwidgets.org>
 # Licence:    wxWindows licence
 ##############################################################################
 
@@ -25,7 +25,7 @@ msg()
 # write all the common options to stdout, massaging them specially if they are
 # meant to be included in a configure input file setup.h.in
 #
-# usage: cat_common_options_for setup_inc.h setup0.h
+# usage: cat_common_options_for setup_inc.h setup.h
 cat_common_options_for()
 {
     # get rid of the copyright header on top of the file
@@ -39,6 +39,11 @@ cat_common_options_for()
         cmd="$cmd | sed -e '/^\/\//d' \
                         -e 's@ *//.*\$@@' \
                         -e 's/# *define \(.\+\) \+1 *\$/#define \1 0/'"
+    elif [ $2 = "build/cmake/setup.h.in" ]; then
+        # The setup.h.in template for cmake needs special processing
+        cmd="$cmd | sed -e '/^\/\//d' \
+                        -e 's@ *//.*\$@@' \
+                        -e 's/# *define \([^ ]\+\) \+\(1\|0\) *\$/#cmakedefine01 \1/'"
     fi
 
     eval $cmd
@@ -47,7 +52,7 @@ cat_common_options_for()
 # update the single setup.h file passed in as the parameter if it is out of
 # date
 #
-# usage: update_single_setup_h {common|MSW} setup_inc.h setup0.h
+# usage: update_single_setup_h {common|MSW} setup_inc.h setup.h
 update_single_setup_h()
 {
     section=$1
@@ -55,25 +60,26 @@ update_single_setup_h()
     setup_inc=$1
     shift
 
-    if [ $setup_inc -ot $1 ]; then
-        echo "Skipping $1 which is already up to date."
-        return 0
-    fi
-
     echo -n "Updating $1 ..."
 
     tmp=$i.$$.tmp
     sed -e "/^\/\* --- start $section options --- \*\/\$/q" $1 > $tmp &&
     cat_common_options_for $setup_inc $1 >> $tmp &&
-    sed -n -e "/^\/\* --- end $section options --- \*\/\$/,\$p" $1 >> $tmp &&
-    mv $tmp $1
+    sed -n -e "/^\/\* --- end $section options --- \*\/\$/,\$p" $1 >> $tmp
 
-    if [ $? -ne 0 ]; then
-        msg " FAILED"
-        error "$0: failed to update file $1"
-        rc=2
+    if cmp -s $1 $tmp; then
+        rm $tmp
+        msg " unchanged"
     else
-        msg " ok"
+        mv $tmp $1
+
+        if [ $? -ne 0 ]; then
+            msg " FAILED"
+            error "$0: failed to update file $1"
+            rc=2
+        else
+            msg " ok"
+        fi
     fi
 }
 
@@ -89,26 +95,35 @@ update_msw_setup_h()
     update_single_setup_h MSW include/wx/msw/setup_inc.h $1
 }
 
+# wrapper for update_single_setup_h which only updates the OSX options
+update_osx_setup_h()
+{
+    update_single_setup_h OSX include/wx/osx/setup_inc.h $1
+}
+
 # entry point
 if [ ! -f wxwin.m4 ]; then
     error "$0: must be ran from root wx directory"
     exit 1
 fi
 
-update_common_setup_h include/wx/motif/setup0.h
-update_common_setup_h include/wx/msw/setup0.h
-update_common_setup_h include/wx/msw/wince/setup.h
-update_common_setup_h include/wx/gtk/setup0.h
-update_common_setup_h include/wx/osx/setup0.h
-update_common_setup_h include/wx/os2/setup0.h
-update_common_setup_h include/wx/univ/setup0.h
+update_common_setup_h include/wx/android/setup.h
+update_common_setup_h include/wx/motif/setup.h
+update_common_setup_h include/wx/msw/setup.h
+update_common_setup_h include/wx/gtk/setup.h
+update_common_setup_h include/wx/osx/setup.h
+update_common_setup_h include/wx/univ/setup.h
 update_common_setup_h setup.h.in
+update_common_setup_h build/cmake/setup.h.in
 
-update_msw_setup_h include/wx/msw/setup0.h
-update_msw_setup_h include/wx/gtk/setup0.h
+update_msw_setup_h include/wx/msw/setup.h
+update_msw_setup_h include/wx/gtk/setup.h
 update_msw_setup_h setup.h.in
+update_msw_setup_h build/cmake/setup.h.in
 
-update_single_setup_h wxUniv include/wx/univ/setup_inc.h include/wx/univ/setup0.h
+update_osx_setup_h include/wx/osx/setup.h
+
+update_single_setup_h wxUniv include/wx/univ/setup_inc.h include/wx/univ/setup.h
 
 exit $rc
 
