Added version 1.0.435

diff --git a/chromium/build/android/adb_gdb b/chromium/build/android/adb_gdb
--- a/chromium/build/android/adb_gdb
+++ b/chromium/build/android/adb_gdb
@@ -15,13 +15,11 @@
 PROGNAME=$(basename "$0")
 PROGDIR=$(dirname "$0")
 
+# Force locale to C to allow recognizing output from subprocesses.
+LC_ALL=C
+
 # Location of Chromium-top-level sources.
 CHROMIUM_SRC=$(cd "$PROGDIR"/../.. >/dev/null && pwd 2>/dev/null)
-
-# Location of Chromium out/ directory.
-if [ -z "$CHROMIUM_OUT_DIR" ]; then
-  CHROMIUM_OUT_DIR=out
-fi
 
 TMPDIR=
 GDBSERVER_PIDFILE=
@@ -186,6 +184,9 @@ for opt; do
     --symbol-dir=*)
       SYMBOL_DIR=$optarg
       ;;
+    --output-dir=*)
+      CHROMIUM_OUTPUT_DIR=$optarg
+      ;;
     --out-dir=*)
       CHROMIUM_OUT_DIR=$optarg
       ;;
@@ -219,11 +220,6 @@ for opt; do
       ;;
   esac
 done
-
-print_help_options () {
-  cat <<EOF
-EOF
-}
 
 if [ "$HELP" ]; then
   if [ "$ADB_GDB_PROGNAME" ]; then
@@ -266,13 +262,11 @@ directory.
 The script tries to find the most recent version of the debug version of
 shared libraries under one of the following directories:
 
-  \$CHROMIUM_SRC/<out>/Release/lib/           (used by Ninja builds)
-  \$CHROMIUM_SRC/<out>/Debug/lib/             (used by Ninja builds)
-  \$CHROMIUM_SRC/<out>/Release/lib.target/    (used by Make builds)
-  \$CHROMIUM_SRC/<out>/Debug/lib.target/      (used by Make builds)
+  \$CHROMIUM_SRC/<out>/lib/                (used by GYP builds)
+  \$CHROMIUM_SRC/<out>/lib.unstripped/     (used by GN builds)
 
-Where <out> is 'out' by default, unless the --out=<name> option is used or
-the CHROMIUM_OUT_DIR environment variable is defined.
+Where <out> is 'out' is determined by CHROMIUM_OUT_DIR, CHROMIUM_OUTPUT_DIR, or
+the --out-dir, --output-dir flags.
 
 You can restrict this search by using --release or --debug to specify the
 build type, or simply use --symbol-dir=<path> to specify the file manually.
@@ -316,7 +310,8 @@ Valid options:
   --sandboxed           Debug first sandboxed process we find.
   --sandboxed=<num>     Debug specific sandboxed process.
   --symbol-dir=<path>   Specify directory with symbol shared libraries.
-  --out-dir=<path>      Specify the out directory.
+  --out-dir=<path>      Specify the out directory (e.g. "out").
+  --output-dir=<path>   Specify the output directory (e.g. "out/Debug").
   --package-name=<name> Specify package name (alternative to 1st argument).
   --privileged          Debug first privileged process we find.
   --privileged=<num>    Debug specific privileged process.
@@ -691,7 +686,7 @@ if [ "$START" ]; then
 package is installed?"
 fi
 
-# Return the timestamp of a given time, as number of seconds since epoch.
+# Return the timestamp of a given file, as number of seconds since epoch.
 # $1: file path
 # Out: file timestamp
 get_file_timestamp () {
@@ -700,24 +695,37 @@ get_file_timestamp () {
 
 # Detect the build type and symbol directory. This is done by finding
 # the most recent sub-directory containing debug shared libraries under
-# $CHROMIUM_SRC/$CHROMIUM_OUT_DIR/
+# (in order of priority):
+# 1. $CHROMIUM_OUTPUT_DIR
+# 2. $CHROMIUM_SRC/$CHROMIUM_OUT_DIR/$BUILDTYPE (if $BUILDTYPE is set)
+# 3. $CHROMIUM_SRC/$CHROMIUM_OUT_DIR/{Debug,Release}
 #
-# $1: $BUILDTYPE value, can be empty
 # Out: nothing, but this sets SYMBOL_DIR
 #
 detect_symbol_dir () {
-  local SUBDIRS SUBDIR LIST DIR DIR_LIBS TSTAMP
-  # Note: Ninja places debug libraries under out/$BUILDTYPE/lib/, while
-  # Make places then under out/$BUILDTYPE/lib.target.
-  if [ "$1" ]; then
-    SUBDIRS="$1/lib $1/lib.target"
+  local PARENT_DIR SUBDIRS SUBDIR LIST DIR DIR_LIBS TSTAMP
+  # GYP places unstripped libraries under out/$BUILDTYPE/lib
+  # GN places them under out/$BUILDTYPE/lib.unstripped
+  if [[ -n "$CHROMIUM_OUTPUT_DIR" ]]; then
+    PARENT_DIR="$CHROMIUM_OUTPUT_DIR"
+    SUBDIRS="lib.unstripped lib"
   else
-    SUBDIRS="Release/lib Debug/lib Release/lib.target Debug/lib.target"
+    PARENT_DIR="$CHROMIUM_OUT_DIR"
+    if [[ -n "$BUILDTYPE" ]]; then
+      PARENT_DIR="$PARENT_DIR/$BUILDTYPE"
+      SUBDIRS="lib.unstripped lib"
+    else
+      SUBDIRS="Release/lib.unstripped Debug/lib.unstripped "
+      SUBDIRS+="Release/lib Debug/lib"
+    fi
+  fi
+  if [[ ! -e "$PARENT_DIR" ]]; then
+    PARENT_DIR="$CHROMIUM_SRC/$PARENT_DIR"
   fi
   LIST=$TMPDIR/scan-subdirs-$$.txt
   printf "" > "$LIST"
   for SUBDIR in $SUBDIRS; do
-    DIR=$CHROMIUM_SRC/$CHROMIUM_OUT_DIR/$SUBDIR
+    DIR="$PARENT_DIR/$SUBDIR"
     if [ -d "$DIR" ]; then
       # Ignore build directories that don't contain symbol versions
       # of the shared libraries.
@@ -733,22 +741,17 @@ detect_symbol_dir () {
   SUBDIR=$(cat $LIST | sort -r | head -1 | cut -d" " -f2)
   rm -f "$LIST"
 
-  if [ -z "$SUBDIR" ]; then
-    if [ -z "$1" ]; then
-      panic "Could not find any build directory under \
-$CHROMIUM_SRC/$CHROMIUM_OUT_DIR. Please build the program first!"
-    else
-      panic "Could not find any $1 directory under \
-$CHROMIUM_SRC/$CHROMIUM_OUT_DIR. Check your build type!"
-    fi
+  if [[ -z "$SUBDIR" ]]; then
+    panic "Could not find any build directory under \
+$PARENT_DIR/{${SUBDIRS// /,}}. Please build the program first!"
   fi
 
-  SYMBOL_DIR=$CHROMIUM_SRC/$CHROMIUM_OUT_DIR/$SUBDIR
+  SYMBOL_DIR=$PARENT_DIR/$SUBDIR
   log "Auto-config: --symbol-dir=$SYMBOL_DIR"
 }
 
 if [ -z "$SYMBOL_DIR" ]; then
-  detect_symbol_dir "$BUILDTYPE"
+  detect_symbol_dir
 fi
 
 # Allow several concurrent debugging sessions
@@ -767,6 +770,7 @@ PULL_LIBS_DIR=${PULL_LIBS_DIR:-$DEFAULT_PULL_LIBS_DIR}
 
 HOST_FINGERPRINT=
 DEVICE_FINGERPRINT=$(adb_shell getprop ro.build.fingerprint)
+[[ "$DEVICE_FINGERPRINT" ]] || panic "Failed to get the device fingerprint"
 log "Device build fingerprint: $DEVICE_FINGERPRINT"
 
 # If --pull-libs-dir is not specified, and this is a platform build, look
@@ -794,11 +798,11 @@ fi
 # fingerprints of the device, and the cached system libraries on the host.
 #
 if [ -z "$NO_PULL_LIBS" -a -z "$PULL_LIBS" ]; then
-  if [ ! -f "$PULL_LIBS_DIR/build.prop" ]; then
+  if [ ! -f "$PULL_LIBS_DIR/build.fingerprint" ]; then
     log "Auto-config: --pull-libs  (no cached libraries)"
     PULL_LIBS=true
   else
-    HOST_FINGERPRINT=$(get_build_fingerprint_from "$PULL_LIBS_DIR/build.prop")
+    HOST_FINGERPRINT=$(< "$PULL_LIBS_DIR/build.fingerprint")
     log "Host build fingerprint:   $HOST_FINGERPRINT"
     if [ "$HOST_FINGERPRINT" == "$DEVICE_FINGERPRINT" ]; then
       log "Auto-config: --no-pull-libs (fingerprint match)"
@@ -897,7 +901,6 @@ log "Command suffix: '$COMMAND_SUFFIX'"
 # we need by looking at /proc/$PID/maps instead
 if [ "$PULL_LIBS" -a -z "$NO_PULL_LIBS" ]; then
   echo "Extracting system libraries into: $PULL_LIBS_DIR"
-  rm -f $PULL_LIBS_DIR/build.prop
   MAPPINGS=$(adb_shell $COMMAND_PREFIX cat /proc/$PID/maps $COMMAND_SUFFIX)
   if [ $? != 0 ]; then
     echo "ERROR: Could not list process's memory mappings."
@@ -907,6 +910,8 @@ if [ "$PULL_LIBS" -a -z "$NO_PULL_LIBS" ]; then
       panic "Use --su-prefix if the application is not debuggable."
     fi
   fi
+  # Remove the fingerprint file in case pulling one of the libs fails.
+  rm -f "$PULL_LIBS_DIR/build.fingerprint"
   SYSTEM_LIBS=$(echo "$MAPPINGS" | \
       awk '$6 ~ /\/system\/.*\.so$/ { print $6; }' | sort -u)
   for SYSLIB in /system/bin/linker $SYSTEM_LIBS; do
@@ -916,9 +921,8 @@ if [ "$PULL_LIBS" -a -z "$NO_PULL_LIBS" ]; then
     mkdir -p "$DST_DIR" && adb pull $SYSLIB "$DST_FILE" 2>/dev/null
     fail_panic "Could not pull $SYSLIB from device !?"
   done
-  echo "Pulling device build.prop"
-  adb pull /system/build.prop $PULL_LIBS_DIR/build.prop
-  fail_panic "Could not pull device build.prop !?"
+  echo "Writing the device fingerprint"
+  echo "$DEVICE_FINGERPRINT" > "$PULL_LIBS_DIR/build.fingerprint"
 fi
 
 # Find all the sub-directories of $PULL_LIBS_DIR, up to depth 4
@@ -946,10 +950,16 @@ TARGET_PORT=$PORT
 
 # Select correct app_process for architecture.
 case $TARGET_ARCH in
-      arm|x86|mips) GDBEXEC=app_process;;
+      arm|x86|mips) GDBEXEC=app_process32;;
       arm64|x86_64) GDBEXEC=app_process64;;
       *) fail_panic "Unknown app_process for architecture!";;
 esac
+
+# Default to app_process if bit-width specific process isn't found.
+adb_shell ls /system/bin/$GDBEXEC
+if [ $? != 0 ]; then
+    GDBEXEC=app_process
+fi
 
 # Detect AddressSanitizer setup on the device. In that case app_process is a
 # script, and the real executable is app_process.real.
@@ -980,9 +990,9 @@ host:localhost:$HOST_PORT to device:localhost:$TARGET_PORT!"
 log "Starting gdbserver in the background:"
 GDBSERVER_LOG=$TMPDIR/gdbserver-$TMP_ID.log
 log "adb shell $COMMAND_PREFIX $TARGET_GDBSERVER :$TARGET_PORT \
---attach $PID $COMMAND_SUFFIX"
-("$ADB" shell $COMMAND_PREFIX $TARGET_GDBSERVER :$TARGET_PORT \
- --attach $PID $COMMAND_SUFFIX > $GDBSERVER_LOG 2>&1) &
+  --attach $PID $COMMAND_SUFFIX"
+"$ADB" shell $COMMAND_PREFIX $TARGET_GDBSERVER :$TARGET_PORT \
+  --attach $PID $COMMAND_SUFFIX > $GDBSERVER_LOG 2>&1 &
 GDBSERVER_PID=$!
 echo "$GDBSERVER_PID" > $GDBSERVER_PIDFILE
 log "background job pid: $GDBSERVER_PID"
