Added version 2.0.1309

diff --git a/chromium/build/android/adb_gdb b/chromium/build/android/adb_gdb
--- a/chromium/build/android/adb_gdb
+++ b/chromium/build/android/adb_gdb
@@ -66,7 +66,8 @@ log () {
   fi
 }
 
-DEFAULT_PULL_LIBS_DIR=/tmp/$USER-adb-gdb-libs
+DEFAULT_PULL_LIBS_DIR="/tmp/adb-gdb-support-$USER"
+IDE_DIR="$DEFAULT_PULL_LIBS_DIR"
 
 # NOTE: Allow wrapper scripts to set various default through ADB_GDB_XXX
 # environment variables. This is only for cosmetic reasons, i.e. to
@@ -77,11 +78,11 @@ PROGNAME=${ADB_GDB_PROGNAME:-$(basename "$0")}
 
 ADB=
 ANNOTATE=
-FORCE=
 CGDB=
 GDBINIT=
 GDBSERVER=
 HELP=
+IDE=
 NDK_DIR=
 NO_PULL_LIBS=
 PACKAGE_NAME=
@@ -109,9 +110,6 @@ for opt; do
     --annotate=3)
       ANNOTATE=$optarg
       ;;
-    --force)
-      FORCE=true
-      ;;
     --gdbserver=*)
       GDBSERVER=$optarg
       ;;
@@ -120,6 +118,9 @@ for opt; do
       ;;
     --help|-h|-?)
       HELP=true
+      ;;
+    --ide)
+      IDE=true
       ;;
     --ndk-dir=*)
       NDK_DIR=$optarg
@@ -275,7 +276,6 @@ Valid options:
   --package-name=<name> Specify package name (alternative to 1st argument).
   --program-name=<name> Specify program name (cosmetic only).
   --pid=<pid>           Specify application process pid.
-  --force               Kill any previous debugging session, if any.
   --attach-delay=<num>  Seconds to wait for gdbserver to attach to the
                         remote process before starting gdb. Default 1.
                         <num> may be a float if your sleep(1) supports it.
@@ -288,6 +288,7 @@ Valid options:
   --adb=<file>          Specify host ADB binary.
   --device=<file>       ADB device serial to use (-s flag).
   --port=<port>         Specify the tcp port to use.
+  --ide                 Forward gdb port, but do not enter gdb console.
 
   --su-prefix=<prefix>  Prepend <prefix> to 'adb shell' commands that are
                         run by this script. This can be useful to use
@@ -319,7 +320,7 @@ if [[ -z "$SYMBOL_DIR" && -z "$CHROMIUM_OUTPUT_DIR" ]]; then
 fi
 
 if ls *.so >/dev/null 2>&1; then
-  panic ".so files found in your working directory. These will conflict with " \
+  panic ".so files found in your working directory. These will conflict with" \
       "library lookup logic. Change your working directory and try again."
 fi
 
@@ -487,6 +488,12 @@ get_ndk_host_arch () {
   if [ -z "$NDK_HOST_ARCH" ]; then
     HOST_OS=$(get_ndk_host_system)
     HOST_ARCH=$(uname -p)
+    if [ "$HOST_ARCH" = "unknown" ]; then
+      # In case where "-p" returns "unknown" just use "-m" (machine hardware
+      # name). According to this patch from Fedora "-p" is equivalent to "-m"
+      # anyway: https://goo.gl/Pd47x3
+      HOST_ARCH=$(uname -m)
+    fi
     case $HOST_ARCH in
       i?86) NDK_HOST_ARCH=x86;;
       x86_64|amd64) NDK_HOST_ARCH=x86_64;;
@@ -683,18 +690,6 @@ mkdir -p "$TMPDIR" && rm -rf "$TMPDIR"/*
 
 GDBSERVER_PIDFILE="$TMPDIR"/gdbserver-$TMP_ID.pid
 
-# If --force is specified, try to kill any gdbserver process started by the
-# same user on the device. Normally, these are killed automatically by the
-# script on exit, but there are a few corner cases where this would still
-# be needed.
-if [ "$FORCE" ]; then
-  GDBSERVER_PIDS=$(adb_shell ps | awk '$9 ~ /gdbserver/ { print $2; }')
-  for GDB_PID in $GDBSERVER_PIDS; do
-    log "Killing previous gdbserver (PID=$GDB_PID)"
-    adb_shell kill -9 $GDB_PID
-  done
-fi
-
 # Return the timestamp of a given file, as number of seconds since epoch.
 # $1: file path
 # Out: file timestamp
@@ -708,14 +703,31 @@ fail_panic "Failed to run-as $PACKAGE_NAME, is the app debuggable?"
 TARGET_GDBSERVER="$APP_DATA_DIR/gdbserver-adb-gdb-$TMP_ID"
 TMP_TARGET_GDBSERVER=/data/local/tmp/gdbserver-adb-gdb-$TMP_ID
 
-# Return the build fingerprint contained in a build.prop file.
-# $1: path to build.prop file
-get_build_fingerprint_from () {
-  cat "$1" | grep -e '^ro.build.fingerprint=' | cut -d= -f2
-}
+# Select correct app_process for architecture.
+case $TARGET_ARCH in
+      arm|x86|mips) GDBEXEC=app_process32;;
+      arm64|x86_64) GDBEXEC=app_process64; SUFFIX_64_BIT=64;;
+      *) panic "Unknown app_process for architecture!";;
+esac
 
+# Default to app_process if bit-width specific process isn't found.
+adb_shell ls /system/bin/$GDBEXEC > /dev/null
+if [ $? != 0 ]; then
+    GDBEXEC=app_process
+fi
+
+# Detect AddressSanitizer setup on the device. In that case app_process is a
+# script, and the real executable is app_process.real.
+GDBEXEC_ASAN=app_process.real
+adb_shell ls /system/bin/$GDBEXEC_ASAN > /dev/null
+if [ $? == 0 ]; then
+    GDBEXEC=$GDBEXEC_ASAN
+fi
 
 ORG_PULL_LIBS_DIR=$PULL_LIBS_DIR
+if [[ -n "$ANDROID_SERIAL" ]]; then
+  DEFAULT_PULL_LIBS_DIR="$DEFAULT_PULL_LIBS_DIR/$ANDROID_SERIAL-$SUFFIX_64_BIT"
+fi
 PULL_LIBS_DIR=${PULL_LIBS_DIR:-$DEFAULT_PULL_LIBS_DIR}
 
 HOST_FINGERPRINT=
@@ -723,44 +735,18 @@ DEVICE_FINGERPRINT=$(adb_shell getprop ro.build.fingerprint)
 [[ "$DEVICE_FINGERPRINT" ]] || panic "Failed to get the device fingerprint"
 log "Device build fingerprint: $DEVICE_FINGERPRINT"
 
-# If --pull-libs-dir is not specified, and this is a platform build, look
-# if we can use the symbolic libraries under $ANDROID_PRODUCT_OUT/symbols/
-# directly, if the build fingerprint matches the device.
-if [ -z "$ORG_PULL_LIBS_DIR" -a \
-     "$ANDROID_PRODUCT_OUT" -a \
-     -f "$ANDROID_PRODUCT_OUT/system/build.prop" ]; then
-  ANDROID_FINGERPRINT=$(get_build_fingerprint_from \
-                        "$ANDROID_PRODUCT_OUT"/system/build.prop)
-  log "Android build fingerprint:  $ANDROID_FINGERPRINT"
-  if [ "$ANDROID_FINGERPRINT" = "$DEVICE_FINGERPRINT" ]; then
-    log "Perfect match!"
-    PULL_LIBS_DIR=$ANDROID_PRODUCT_OUT/symbols
-    HOST_FINGERPRINT=$ANDROID_FINGERPRINT
-    if [ "$PULL_LIBS" ]; then
-      log "Ignoring --pull-libs since the device and platform build \
-fingerprints match."
-      NO_PULL_LIBS=true
-    fi
-  fi
-fi
-
-# If neither --pull-libs an --no-pull-libs were specified, check the build
-# fingerprints of the device, and the cached system libraries on the host.
-#
-if [ -z "$NO_PULL_LIBS" -a -z "$PULL_LIBS" ]; then
-  if [ ! -f "$PULL_LIBS_DIR/build.fingerprint" ]; then
-    log "Auto-config: --pull-libs  (no cached libraries)"
-    PULL_LIBS=true
+if [ ! -f "$PULL_LIBS_DIR/build.fingerprint" ]; then
+  log "Auto-config: --pull-libs  (no cached libraries)"
+  PULL_LIBS=true
+else
+  HOST_FINGERPRINT=$(< "$PULL_LIBS_DIR/build.fingerprint")
+  log "Host build fingerprint:   $HOST_FINGERPRINT"
+  if [ "$HOST_FINGERPRINT" == "$DEVICE_FINGERPRINT" ]; then
+    log "Auto-config: --no-pull-libs (fingerprint match)"
+    NO_PULL_LIBS=true
   else
-    HOST_FINGERPRINT=$(< "$PULL_LIBS_DIR/build.fingerprint")
-    log "Host build fingerprint:   $HOST_FINGERPRINT"
-    if [ "$HOST_FINGERPRINT" == "$DEVICE_FINGERPRINT" ]; then
-      log "Auto-config: --no-pull-libs (fingerprint match)"
-      NO_PULL_LIBS=true
-    else
-      log "Auto-config: --pull-libs  (fingerprint mismatch)"
-      PULL_LIBS=true
-    fi
+    log "Auto-config: --pull-libs  (fingerprint mismatch)"
+    PULL_LIBS=true
   fi
 fi
 
@@ -836,7 +822,7 @@ if [ "$PULL_LIBS" -a -z "$NO_PULL_LIBS" ]; then
   rm -f "$PULL_LIBS_DIR/build.fingerprint"
   SYSTEM_LIBS=$(echo "$MAPPINGS" | \
       awk '$6 ~ /\/system\/.*\.so$/ { print $6; }' | sort -u)
-  for SYSLIB in /system/bin/linker $SYSTEM_LIBS; do
+  for SYSLIB in /system/bin/linker$SUFFIX_64_BIT $SYSTEM_LIBS; do
     echo "Pulling from device: $SYSLIB"
     DST_FILE=$PULL_LIBS_DIR$SYSLIB
     DST_DIR=$(dirname "$DST_FILE")
@@ -847,16 +833,21 @@ if [ "$PULL_LIBS" -a -z "$NO_PULL_LIBS" ]; then
   echo "$DEVICE_FINGERPRINT" > "$PULL_LIBS_DIR/build.fingerprint"
 fi
 
+# Pull the app_process binary from the device.
+log "Pulling $GDBEXEC from device"
+"$ADB" pull /system/bin/$GDBEXEC "$TMPDIR"/$GDBEXEC &>/dev/null
+fail_panic "Could not retrieve $GDBEXEC from the device!"
+
 # Find all the sub-directories of $PULL_LIBS_DIR, up to depth 4
 # so we can add them to solib-search-path later.
 SOLIB_DIRS=$(find $PULL_LIBS_DIR -mindepth 1 -maxdepth 4 -type d | \
              grep -v "^$" | tr '\n' ':')
 SOLIB_DIRS=${SOLIB_DIRS%:}  # Strip trailing :
 
-# This is a re-implementation of gdbclient, where we use compatible
-# versions of gdbserver and $GDBNAME to ensure that everything works
-# properly.
-#
+# Applications with minSdkVersion >= 24 will have their data directories
+# created with rwx------ permissions, preventing adbd from forwarding to
+# the gdbserver socket.
+adb_shell $COMMAND_PREFIX chmod a+x $APP_DATA_DIR $COMMAND_SUFFIX
 
 # Push gdbserver to the device
 log "Pushing gdbserver $GDBSERVER to $TARGET_GDBSERVER"
@@ -872,32 +863,6 @@ fi
 HOST_PORT=$PORT
 TARGET_DOMAIN_SOCKET=$APP_DATA_DIR/gdb-socket-$HOST_PORT
 
-# Select correct app_process for architecture.
-case $TARGET_ARCH in
-      arm|x86|mips) GDBEXEC=app_process32;;
-      arm64|x86_64) GDBEXEC=app_process64;;
-      *) panic "Unknown app_process for architecture!";;
-esac
-
-# Default to app_process if bit-width specific process isn't found.
-adb_shell ls /system/bin/$GDBEXEC
-if [ $? != 0 ]; then
-    GDBEXEC=app_process
-fi
-
-# Detect AddressSanitizer setup on the device. In that case app_process is a
-# script, and the real executable is app_process.real.
-GDBEXEC_ASAN=app_process.real
-adb_shell ls /system/bin/$GDBEXEC_ASAN
-if [ $? == 0 ]; then
-    GDBEXEC=$GDBEXEC_ASAN
-fi
-
-# Pull the app_process binary from the device.
-log "Pulling $GDBEXEC from device"
-"$ADB" pull /system/bin/$GDBEXEC "$TMPDIR"/$GDBEXEC &>/dev/null
-fail_panic "Could not retrieve $GDBEXEC from the device!"
-
 # Setup network redirection
 log "Setting network redirection (host:$HOST_PORT -> device:$TARGET_DOMAIN_SOCKET)"
 "$ADB" forward tcp:$HOST_PORT localfilesystem:$TARGET_DOMAIN_SOCKET
@@ -911,37 +876,50 @@ host:localhost:$HOST_PORT to device:$TARGET_DOMAIN_SOCKET"
 # program as root, which requires of course root privileges.
 # Maybe we should add a --root option to enable this?
 #
-log "Starting gdbserver in the background:"
-GDBSERVER_LOG=$TMPDIR/gdbserver-$TMP_ID.log
-log "adb shell $COMMAND_PREFIX $TARGET_GDBSERVER \
-  --once +$TARGET_DOMAIN_SOCKET \
-  --attach $PID $COMMAND_SUFFIX"
-"$ADB" shell $COMMAND_PREFIX $TARGET_GDBSERVER \
-  --once +$TARGET_DOMAIN_SOCKET \
-  --attach $PID $COMMAND_SUFFIX > $GDBSERVER_LOG 2>&1 &
-GDBSERVER_PID=$!
-echo "$GDBSERVER_PID" > $GDBSERVER_PIDFILE
-log "background job pid: $GDBSERVER_PID"
 
-# Sleep to allow gdbserver to attach to the remote process and be
-# ready to connect to.
-log "Sleeping ${ATTACH_DELAY}s to ensure gdbserver is alive"
-sleep "$ATTACH_DELAY"
-log "Job control: $(jobs -l)"
-STATE=$(jobs -l | awk '$2 == "'$GDBSERVER_PID'" { print $3; }')
-if [ "$STATE" != "Running" ]; then
-  echo "ERROR: GDBServer either failed to run or attach to PID $PID!"
-  echo "Here is the output from gdbserver (also try --verbose for more):"
-  echo "===== gdbserver.log start ====="
-  cat $GDBSERVER_LOG
-  echo ="===== gdbserver.log end ======"
-  exit 1
-fi
+for i in 1 2; do
+  log "Starting gdbserver in the background:"
+  GDBSERVER_LOG=$TMPDIR/gdbserver-$TMP_ID.log
+  log "adb shell $COMMAND_PREFIX $TARGET_GDBSERVER \
+    --once +$TARGET_DOMAIN_SOCKET \
+    --attach $PID $COMMAND_SUFFIX"
+  "$ADB" shell $COMMAND_PREFIX $TARGET_GDBSERVER \
+    --once +$TARGET_DOMAIN_SOCKET \
+    --attach $PID $COMMAND_SUFFIX > $GDBSERVER_LOG 2>&1 &
+  GDBSERVER_PID=$!
+  echo "$GDBSERVER_PID" > $GDBSERVER_PIDFILE
+  log "background job pid: $GDBSERVER_PID"
+
+  # Sleep to allow gdbserver to attach to the remote process and be
+  # ready to connect to.
+  log "Sleeping ${ATTACH_DELAY}s to ensure gdbserver is alive"
+  sleep "$ATTACH_DELAY"
+  log "Job control: $(jobs -l)"
+  STATE=$(jobs -l | awk '$2 == "'$GDBSERVER_PID'" { print $3; }')
+  if [ "$STATE" != "Running" ]; then
+    pid_msg=$(grep "is already traced by process" $GDBSERVER_LOG 2>/dev/null)
+    if [[ -n "$pid_msg" ]]; then
+      old_pid=${pid_msg##* }
+      old_pid=${old_pid//[$'\r\n']}  # Trim trailing \r.
+      echo "Killing previous gdb server process (pid=$old_pid)"
+      adb_shell $COMMAND_PREFIX kill -9 $old_pid $COMMAND_SUFFIX
+      continue
+    fi
+    echo "ERROR: GDBServer either failed to run or attach to PID $PID!"
+    echo "Here is the output from gdbserver (also try --verbose for more):"
+    echo "===== gdbserver.log start ====="
+    cat $GDBSERVER_LOG
+    echo ="===== gdbserver.log end ======"
+    exit 1
+  fi
+  break
+done
 
 # Generate a file containing useful GDB initialization commands
 readonly COMMANDS=$TMPDIR/gdb.init
 log "Generating GDB initialization commands file: $COMMANDS"
-cat > $COMMANDS <<EOF
+cat > "$COMMANDS" <<EOF
+set osabi GNU/Linux  # Copied from ndk-gdb.py.
 set print pretty 1
 python
 import sys
@@ -955,7 +933,11 @@ file $TMPDIR/$GDBEXEC
 directory $CHROMIUM_SRC
 set solib-absolute-prefix $PULL_LIBS_DIR
 set solib-search-path $SOLIB_DIRS:$PULL_LIBS_DIR:$SYMBOL_DIR
-echo Attaching and reading symbols, this may take a while.."
+EOF
+
+if [[ -z "$IDE" ]]; then
+  cat >> "$COMMANDS" <<EOF
+echo Attaching and reading symbols, this may take a couple minutes..."
 python
 # Copied from ndk-gdb.py:
 def target_remote_with_retry(target, timeout_seconds):
@@ -976,21 +958,45 @@ def target_remote_with_retry(target, timeout_seconds):
 target_remote_with_retry(':$HOST_PORT', 5)
 end
 EOF
+fi
 
 if [ "$GDBINIT" ]; then
-  cat "$GDBINIT" >> $COMMANDS
+  cat "$GDBINIT" >> "$COMMANDS"
 fi
 
 if [ "$VERBOSE" -gt 0 ]; then
   echo "### START $COMMANDS"
-  cat $COMMANDS
+  cat "$COMMANDS"
   echo "### END $COMMANDS"
 fi
 
-log "Launching gdb client: $GDB $GDB_ARGS -x $COMMANDS"
-if [ "$CGDB" ]; then
-  $CGDB -d $GDB -- $GDB_ARGS -x $COMMANDS
+if [ "$IDE" ]; then
+  mkdir -p "$IDE_DIR"
+  SYM_GDB="$IDE_DIR/gdb"
+  SYM_EXE="$IDE_DIR/app_process"
+  SYM_INIT="$IDE_DIR/gdbinit"
+  ln -sf "$TMPDIR/$GDBEXEC" "$SYM_EXE"
+  ln -sf "$COMMANDS" "$SYM_INIT"
+  # gdb doesn't work when symlinked, so create a wrapper.
+  echo
+  cat > $SYM_GDB <<EOF
+#!/bin/sh
+exec $GDB "\$@"
+EOF
+  chmod u+x $SYM_GDB
+
+  echo "GDB server listening on: localhost:$PORT"
+  echo "GDB wrapper script: $SYM_GDB"
+  echo "App executable: $SYM_EXE"
+  echo "gdbinit: $SYM_INIT"
+  echo "Showing gdbserver logs. Press Ctrl-C to disconnect."
+  tail -f "$GDBSERVER_LOG"
 else
-  $GDB $GDB_ARGS -x $COMMANDS
+  log "Launching gdb client: $GDB $GDB_ARGS -x $COMMANDS"
+  echo "Server log: $GDBSERVER_LOG"
+  if [ "$CGDB" ]; then
+    $CGDB -d $GDB -- $GDB_ARGS -x "$COMMANDS"
+  else
+    $GDB $GDB_ARGS -x "$COMMANDS"
+  fi
 fi
-rm -f "$GDBSERVER_PIDFILE"
