Added version 1.1.453

diff --git a/chromium/build/android/adb_gdb b/chromium/build/android/adb_gdb
--- a/chromium/build/android/adb_gdb
+++ b/chromium/build/android/adb_gdb
@@ -84,8 +84,6 @@ PROGNAME=${ADB_GDB_PROGNAME:-$(basename "$0")}
 ACTIVITY=$DEFAULT_ACTIVITY
 ADB=
 ANNOTATE=
-# Note: Ignore BUILDTYPE variable, because the Ninja build doesn't use it.
-BUILDTYPE=
 FORCE=
 GDBEXEPOSTFIX=gdb
 GDBINIT=
@@ -104,6 +102,7 @@ PULL_LIBS_DIR=
 SANDBOXED=
 SANDBOXED_INDEX=
 START=
+ATTACH_DELAY=1
 SU_PREFIX=
 SYMBOL_DIR=
 TARGET_ARCH=
@@ -178,17 +177,17 @@ for opt; do
     --start)
       START=true
       ;;
+    --attach-delay=*)
+      ATTACH_DELAY=$optarg
+      ;;
     --su-prefix=*)
       SU_PREFIX=$optarg
       ;;
     --symbol-dir=*)
       SYMBOL_DIR=$optarg
       ;;
-    --output-dir=*)
+    --output-directory=*)
       CHROMIUM_OUTPUT_DIR=$optarg
-      ;;
-    --out-dir=*)
-      CHROMIUM_OUT_DIR=$optarg
       ;;
     --target-arch=*)
       TARGET_ARCH=$optarg
@@ -202,14 +201,8 @@ for opt; do
     --verbose)
       VERBOSE=$(( $VERBOSE + 1 ))
       ;;
-    --debug)
-      BUILDTYPE=Debug
-      ;;
-    --release)
-      BUILDTYPE=Release
-      ;;
     -*)
-      panic "Unknown option $OPT, see --help." >&2
+      panic "Unknown option $opt, see --help." >&2
       ;;
     *)
       if [ "$PACKAGE_NAME" ]; then
@@ -265,11 +258,9 @@ shared libraries under one of the following directories:
   \$CHROMIUM_SRC/<out>/lib/                (used by GYP builds)
   \$CHROMIUM_SRC/<out>/lib.unstripped/     (used by GN builds)
 
-Where <out> is 'out' is determined by CHROMIUM_OUT_DIR, CHROMIUM_OUTPUT_DIR, or
-the --out-dir, --output-dir flags.
+Where <out> is determined by CHROMIUM_OUTPUT_DIR, or --output-directory.
 
-You can restrict this search by using --release or --debug to specify the
-build type, or simply use --symbol-dir=<path> to specify the file manually.
+You can set the path manually via --symbol-dir.
 
 The script tries to extract the target architecture from your target device,
 but if this fails, will default to 'arm'. Use --target-arch=<name> to force
@@ -310,8 +301,7 @@ Valid options:
   --sandboxed           Debug first sandboxed process we find.
   --sandboxed=<num>     Debug specific sandboxed process.
   --symbol-dir=<path>   Specify directory with symbol shared libraries.
-  --out-dir=<path>      Specify the out directory (e.g. "out").
-  --output-dir=<path>   Specify the output directory (e.g. "out/Debug").
+  --output-directory=<path> Specify the output directory (e.g. "out/Debug").
   --package-name=<name> Specify package name (alternative to 1st argument).
   --privileged          Debug first privileged process we find.
   --privileged=<num>    Debug specific privileged process.
@@ -319,6 +309,9 @@ Valid options:
   --pid=<pid>           Specify application process pid.
   --force               Kill any previous debugging session, if any.
   --start               Start package's activity on device.
+  --attach-delay=<num>  Seconds to wait for gdbserver to attach to the
+                        remote process before starting gdb. Default 1.
+                        <num> may be a float if your sleep(1) supports it.
   --ui                  Use gdbtui instead of gdb
   --activity=<name>     Activity name for --start [$DEFAULT_ACTIVITY].
   --annotate=<num>      Enable gdb annotation.
@@ -339,15 +332,24 @@ Valid options:
   --no-pull-libs        Do not extract any system library.
   --libs-dir=<path>     Specify system libraries extraction directory.
 
-  --debug               Use libraries under out/Debug.
-  --release             Use libraries under out/Release.
-
 EOF
   exit 0
 fi
 
 if [ -z "$PACKAGE_NAME" ]; then
   panic "Please specify a package name on the command line. See --help."
+fi
+
+if [[ -z "$CHROMIUM_OUTPUT_DIR" ]]; then
+  if [[ -e "build.ninja" ]]; then
+    CHROMIUM_OUTPUT_DIR=$PWD
+  else
+    panic "Please specify an output directory by using one of:
+       --output-directory=out/Debug
+       CHROMIUM_OUTPUT_DIR=out/Debug
+       Setting working directory to an output directory.
+       See --help."
+   fi
 fi
 
 if [ -z "$NDK_DIR" ]; then
@@ -695,58 +697,25 @@ get_file_timestamp () {
 
 # Detect the build type and symbol directory. This is done by finding
 # the most recent sub-directory containing debug shared libraries under
-# (in order of priority):
-# 1. $CHROMIUM_OUTPUT_DIR
-# 2. $CHROMIUM_SRC/$CHROMIUM_OUT_DIR/$BUILDTYPE (if $BUILDTYPE is set)
-# 3. $CHROMIUM_SRC/$CHROMIUM_OUT_DIR/{Debug,Release}
+# $CHROMIUM_OUTPUT_DIR.
 #
 # Out: nothing, but this sets SYMBOL_DIR
 #
 detect_symbol_dir () {
-  local PARENT_DIR SUBDIRS SUBDIR LIST DIR DIR_LIBS TSTAMP
-  # GYP places unstripped libraries under out/$BUILDTYPE/lib
-  # GN places them under out/$BUILDTYPE/lib.unstripped
-  if [[ -n "$CHROMIUM_OUTPUT_DIR" ]]; then
-    PARENT_DIR="$CHROMIUM_OUTPUT_DIR"
-    SUBDIRS="lib.unstripped lib"
-  else
-    PARENT_DIR="$CHROMIUM_OUT_DIR"
-    if [[ -n "$BUILDTYPE" ]]; then
-      PARENT_DIR="$PARENT_DIR/$BUILDTYPE"
-      SUBDIRS="lib.unstripped lib"
-    else
-      SUBDIRS="Release/lib.unstripped Debug/lib.unstripped "
-      SUBDIRS+="Release/lib Debug/lib"
-    fi
-  fi
+  # GYP places unstripped libraries under out/lib
+  # GN places them under out/lib.unstripped
+  local PARENT_DIR="$CHROMIUM_OUTPUT_DIR"
   if [[ ! -e "$PARENT_DIR" ]]; then
     PARENT_DIR="$CHROMIUM_SRC/$PARENT_DIR"
   fi
-  LIST=$TMPDIR/scan-subdirs-$$.txt
-  printf "" > "$LIST"
-  for SUBDIR in $SUBDIRS; do
-    DIR="$PARENT_DIR/$SUBDIR"
-    if [ -d "$DIR" ]; then
-      # Ignore build directories that don't contain symbol versions
-      # of the shared libraries.
-      DIR_LIBS=$(ls "$DIR"/lib*.so 2>/dev/null)
-      if [ -z "$DIR_LIBS" ]; then
-        echo "No shared libs: $DIR"
-        continue
-      fi
-      TSTAMP=$(get_file_timestamp "$DIR")
-      printf "%s %s\n" "$TSTAMP" "$SUBDIR" >> "$LIST"
+  SYMBOL_DIR="$PARENT_DIR/lib.unstripped"
+  if [[ -z "$(ls "$SYMBOL_DIR"/lib*.so 2>/dev/null)" ]]; then
+    SYMBOL_DIR="$PARENT_DIR/lib"
+    if [[ -z "$(ls "$SYMBOL_DIR"/lib*.so 2>/dev/null)" ]]; then
+      panic "Could not find any symbols under \
+$PARENT_DIR/lib{.unstripped}. Please build the program first!"
     fi
-  done
-  SUBDIR=$(cat $LIST | sort -r | head -1 | cut -d" " -f2)
-  rm -f "$LIST"
-
-  if [[ -z "$SUBDIR" ]]; then
-    panic "Could not find any build directory under \
-$PARENT_DIR/{${SUBDIRS// /,}}. Please build the program first!"
   fi
-
-  SYMBOL_DIR=$PARENT_DIR/$SUBDIR
   log "Auto-config: --symbol-dir=$SYMBOL_DIR"
 }
 
@@ -997,13 +966,14 @@ GDBSERVER_PID=$!
 echo "$GDBSERVER_PID" > $GDBSERVER_PIDFILE
 log "background job pid: $GDBSERVER_PID"
 
-# Check that it is still running after a few seconds. If not, this means we
-# could not properly attach to it
-sleep 2
+# Sleep to allow gdbserver to attach to the remote process and be
+# ready to connect to.
+log "Sleeping ${ATTACH_DELAY}s to allow gdbserver to attach."
+sleep "$ATTACH_DELAY"
 log "Job control: $(jobs -l)"
 STATE=$(jobs -l | awk '$2 == "'$GDBSERVER_PID'" { print $3; }')
 if [ "$STATE" != "Running" ]; then
-  echo "ERROR: GDBServer could not attach to PID $PID!"
+  echo "ERROR: GDBServer either failed to run or attach to PID $PID!"
   if [ $(adb_shell su -c getenforce) != "Permissive" ];  then
     echo "Device mode is Enforcing. Changing Device mode to Permissive "
     $(adb_shell su -c setenforce 0)
